<a href="https://colab.research.google.com/github/Khalid2093/DAV_56/blob/main/DAV_exp1_56.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installing scikit-learn


In [1]:
!pip install -U scikit-learn


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 19.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


# Loadin data set
Importing iris dataset provided by the library itself.

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


# Splitting the data into testing and training

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size = 0.3, random_state = 1
)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


# Model selection
Selecting and training the model

In [5]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size = 0.4, random_state=1
)
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
classifier_knn = KNeighborsClassifier(n_neighbors = 3)
classifier_knn.fit(X_train, y_train)
y_pred = classifier_knn.predict(X_test)
# Finding accuracy by comparing actual response values(y_test)with predicted response value(y_pred)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
# Providing sample data and the model will make prediction out of that data

sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = classifier_knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds]
print("Predictions:", pred_species)

Accuracy: 0.9833333333333333
Predictions: ['versicolor', 'virginica']


# **Importing Scipy**

In [6]:
import numpy as np
import scipy

# Performing Integration of Functions

In [7]:
from scipy.integrate import quad

# Define a function to integrate
def integrand(x):
    return x**2

# Integrate the function from 0 to 1
result, error = quad(integrand, 0, 1)
print("Integration result:", result)

Integration result: 0.33333333333333337


# Optimization
Optimization is a common task in scientific computing. SciPy provides optimization routines to find the minimum or maximum of a function.

In [8]:
from scipy.optimize import minimize

# Define a simple function to minimize
def objective_function(x):
    return x**2 + 5*x + 6

# Minimize the function
result = minimize(objective_function, x0=0)
print("Minimum value:", result.fun)

Minimum value: -0.2499999999999991


# Linear and Matrix Algebra
Determinants and Inverse of matrices can be computed easily using these

In [9]:
from scipy.linalg import inv, det

# Create a matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
A_inv = inv(A)
print("Inverse of A:", A_inv)

# Calculate the determinant of the matrix
A_det = det(A)
print("Determinant of A:", A_det)

Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0


# **R Experiment**

readr library provides a read_csv funtion

In [1]:
library(readr)

In [3]:
df <- read_csv('/content/Data.csv')
print(df)

Rows: 10 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Country, Purchased
dbl (2): Age, Salary

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


# A tibble: 10 × 4
   Country   Age Salary Purchased
   <chr>   <dbl>  <dbl> <chr>    
 1 France     44  72000 No       
 2 Spain      27  48000 Yes      
 3 Germany    30  54000 No       
 4 Spain      38  61000 No       
 5 Germany    40     NA Yes      
 6 France     35  58000 Yes      
 7 Spain      NA  52000 No       
 8 France     48  79000 Yes      
 9 Germany    50  83000 No       
10 France     37  67000 Yes      


In [4]:
library(stringr)

stringr provides function to modify strings

In [5]:
df$Country <- str_to_lower(df$Country)

In [6]:
print(df)

# A tibble: 10 × 4
   Country   Age Salary Purchased
   <chr>   <dbl>  <dbl> <chr>    
 1 france     44  72000 No       
 2 spain      27  48000 Yes      
 3 germany    30  54000 No       
 4 spain      38  61000 No       
 5 germany    40     NA Yes      
 6 france     35  58000 Yes      
 7 spain      NA  52000 No       
 8 france     48  79000 Yes      
 9 germany    50  83000 No       
10 france     37  67000 Yes      
